name: Tests
on: [push]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Configure git for private modules
        env:
          GOPRIVATE: "github.com"
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: git config --global url."https://markbates:${REPO_TOKEN}@github.com".insteadOf "https://github.com"
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Test
        run: |
          go test -v ./...
